#!/usr/bin/env bash

ENCRYPTION_PASSPHRASE=""

git diff --cached --name-only --diff-filter=AM | grep "data.json$" | while read -r file; do
    encrypted_file="${file}.enc"
    openssl aes-256-cbc -in "$file" -out "$encrypted_file" -pass pass:"$ENCRYPTION_PASSPHRASE"
    
    if [ -f "$encrypted_file" ]; then
        rm -f "$file"
        git add "$encrypted_file"
        git reset HEAD "$file"
    else
        echo "Error: Failed to encrypt $file"
        exit 1
    fi
done
